spring:
  application:
    name: hits-internship
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hits-internship}
    username: ${DB_USERNAME:hits-internship}
    password: ${DB_PASSWORD:hits-internship}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
