spring:
  application:
    name: hits-internship
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hits-internship}
    username: ${DB_USERNAME:hits-internship}
    password: ${DB_PASSWORD:hits-internship}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: smtp.yandex.ru
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 465
    protocol: smtps
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

application:
  url: http://localhost:8080
  jwt:
    secret: ${JWT_SECRET:SecretKeyForJwtSecretKeyForJwtSecretKeyForJwtSecretKeyForJwt}
    access:
      expiration-min: ${JWT_EXPIRATION:15}
    refresh:
      expiration-days: ${JWT_REFRESH_EXPIRATION:7}

security:
  permit-all:
    endpoints:
      - pattern: /api/v1/auth/login
        method: POST
      - pattern: /api/v1/specialties
        method: GET
      - pattern: /api/v1/groups
        method: GET

minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:hits-internship}
  url: ${MINIO_URL:http://localhost:9000}