spring:
  application:
    name: hits-internship
  datasource:
    url: ${DB_URL:jdbc:postgresql://hi-db:5432/hits-internship}
    username: ${DB_USERNAME:hits-internship}
    password: ${DB_PASSWORD:hits-internship}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

application:
  url: ${APP_URL:http://localhost:8080}
  jwt:
    secret: ${JWT_SECRET:SecretKeyForJwtSecretKeyForJwtSecretKeyForJwtSecretKeyForJwt}
    access:
      expiration-min: ${JWT_EXPIRATION:1440}

minio:
  access-key: ${MINIO_ACCESS_KEY:hits-admin}
  secret-key: ${MINIO_SECRET_KEY:hits-admin}
  bucket: ${MINIO_BUCKET:hits-internship}
  url: ${MINIO_URL:http://hi-minio:9000}