spring:
  application:
    name: hits-internship
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hits-internship}
    username: ${DB_USERNAME:hits-internship}
    password: ${DB_PASSWORD:hits-internship}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: smtp.yandex.ru
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 465
    protocol: smtps

application:
  url: http://localhost:8080